# Generated by Django 4.2.7 on 2024-08-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0002_shirtcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shirtname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kicksapp.shirtcategory'),
        ),
    ]
