# Generated by Django 4.2.7 on 2024-08-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0003_alter_shirt_shirtname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
