# Generated by Django 4.2.7 on 2024-08-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0005_shirt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
        migrations.DeleteModel(
            name='ShirtCategory',
        ),
    ]
