# Generated by Django 4.2.7 on 2024-08-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0007_shirtcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('upload', models.ImageField(upload_to='images/')),
                ('shirtname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kicksapp.shirtcategory')),
            ],
        ),
    ]
