# Generated by Django 4.2.7 on 2024-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0008_shirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('media', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
