# Generated by Django 4.2.7 on 2024-09-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0012_jacket_name_shirt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='shoename',
            new_name='name',
        ),
    ]
