# Generated by Django 4.2.7 on 2024-09-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0013_rename_shoename_shoes_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='name',
            new_name='shoename',
        ),
    ]
