# Generated by Django 4.2.7 on 2024-09-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0014_rename_name_shoes_shoename'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
