# Generated by Django 4.2.7 on 2024-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0017_shirt_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
