# Generated by Django 4.2.7 on 2024-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shirt',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
    ]
