# Generated by Django 4.2.7 on 2024-11-07 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kicksapp', '0021_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(max_length=30)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('message', models.TextField(default='null', max_length=250)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kicksapp.chatspace')),
            ],
        ),
    ]
