# Generated by Django 4.2.7 on 2024-11-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0022_chatspace_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatspace',
            name='user',
        ),
    ]
