# Generated by Django 4.2.7 on 2024-11-07 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kicksapp', '0023_remove_chatspace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatspace',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
