# Generated by Django 4.2.7 on 2024-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0024_chatspace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='location',
            field=models.CharField(default='unspecified', max_length=20),
        ),
    ]
